http:
  address: ":8080"                   #监听地址
  read_timeout: 10                   #读取超时时长
  write_timeout: 90                  #写入超时时长
  max_header_bytes: 20               #最大的header大小，二进制位长度
  allow_ip: ["127.0.0.1"]                 #白名单ip列表
  time_loc: "Asia/Shanghai"  #设置你的时区,中国内用shanghai chongqing比较多

zap:
  #trace debug info warn error fatal panic
  level: info #logrus.TraceLevel DebugLevel InfoLevel WarnLevel ErrorLevel FatalLevel PanicLevel(logrus高等级的不打印)
  format : logfmt # logfmt | json
  log_path: storage/logs/
  file_name: log # 文件名
  encode_level : CapitalLevelEncoder
  max_size: 10 #Mib,每个日志文件大小
  max_backups: 10 #日志文件个数
  max_age: 1 #day,保留多少天
  show_line: true #显示行
  compress: true #是否压缩
  split_level: true #根据 level 拆分日志
  Log_stdout: true #输出控制台

  #数据库配置
mysql:
  host: '127.0.0.1'
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  name: 'gim'
  user: 'root'
  password: '123456'
  timeout: "10s"
  prefix: "" # 全局表前缀，单独定义 TableName 则不生效
  max_idle_conns: 10
  max_open_conns: 100
  max_life_time : 30
  log_mode: debug # warn | debug
  log_zap: true
