load_type: 2 # 0: 随机   1：平滑  2：平滑加权  3：hash
read_timeout: 10
effective_weight: 5

# 需要把协议头带上，不然 url.parse 不了
http_proxy:
- addr: "http://127.0.0.1:9091"        #监听地址
  weight: 2                   #权重

- addr: "http://127.0.0.1:9092"       #监听地址
  weight: 1                   #权重

- addr: "http://127.0.0.1:9093"       #监听地址
  weight: 1                   #权重

