load_type: 0 # 0: 随机   1：平滑  2：平滑加权  3：hash
effective_weight: 5 # 默认有效权重
connect_timeout : 90 # 建立连接超时, 单位s
header_timeout : 30 # 发送完request后等待serve response的时间
idle_timeout: 30 #链接最大空闲时间, 单位s
max_idle: 30 # 最大空闲链接数

# 需要把协议头带上，不然 url.parse 不了
proxy_nodes:
- addr: "http://127.0.0.1:9091"        #监听地址
  weight: 2                   #权重

- addr: "http://127.0.0.1:9092"       #监听地址
  weight: 1                   #权重

- addr: "http://127.0.0.1:9093"       #监听地址
  weight: 1                   #权重

